name: Katkı yılanını üret

on:
  schedule:
    # Her gün 04:00 UTC
    - cron: "0 4 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/snake.yml"

permissions:
  contents: write

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Yılan animasyonunu üret
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: output dalına yayınla
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
